name: Update Language Stats
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
on:
  schedule:
    # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch:
    # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install PyGithub

      - name: Run script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/update_stats.py

      - name: Push changes
        run: |
            git config --global user.name "CarlosBot"
            git config --global user.email "bot@carlos.dev"
            git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/carloshmarques/carloshmarques.git
            git add README.md
            git commit -m "Atualização automática das linguagens"
            git push origin master
               env:
                 GH_TOKEN: ${{ secrets.GH_TOKEN }}

